// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gshwhakjkhcrpnqmumcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzaHdoYWtqa2hjcnBucW11bWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MTIxNjYsImV4cCI6MjA4OTI4ODE2Nn0.s3bdB5seNPX_uOQWLGsghKuzdHljVMQEZ9XDk1hHr0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});